apiVersion: artifacthub.io/v1alpha1
kind: Repository
metadata:
  name: vault-airgap-chart
  labels:
    category: helm
spec:
  repositoryID: ab751316-b24c-43b3-9cad-a9158ff14558
  type: helm
  url: https://kazeemayeed.github.io/vault-airgap-chart/
owners:
  - name: kazeemayeed
    email: kazeemayeed@gmail.com
