apiVersion: v2
name: vault-airgap
description: A production-grade, air-gapped Helm chart for deploying Vault securely in restricted networks.
type: application
version: 1.0.1
appVersion: "1.13.0"
keywords:
  - vault
  - airgap
  - security
home: https://www.vaultproject.io/
