replicaCount: 1

image:
  repository: myregistry.local/vault
  tag: "1.13.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8200

serviceAccount:
  create: true
  name: ""

rbac:
  create: true

persistence:
  enabled: true
  size: 8Gi
  storageClass: ""

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

backup:
  enabled: false
  schedule: "0 2 * * *"
  retentionDays: 7

lifecycleHooks:
  preInstall:
    - name: init-config
      command: ["/bin/sh", "-c"]
      args: ["echo 'Running pre-install hook for config setup'"]
  postInstall:
    - name: notify
      command: ["/bin/sh", "-c"]
      args: ["echo 'Vault installation completed'"]
