apiVersion: batch/v1
kind: Job
metadata:
  name: vault-pre-install
  annotations:
    "helm.sh/hook": pre-install
spec:
  template:
    spec:
      containers:
        - name: init
          image: busybox
          command: ['sh', '-c', 'echo Pre-install tasks completed']
      restartPolicy: Never