{{- if .Values.backup.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: vault-backup
spec:
  schedule: "{{ .Values.backup.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: {{ .Values.backup.image }}
              command: ["/bin/sh", "-c", "echo Backup logic goes here"]
          restartPolicy: OnFailure
{{- end }}