apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
spec:
  selector:
    matchLabels:
      app: vault
  serviceName: "vault"
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8200
              name: http
          volumeMounts:
            - name: config
              mountPath: /vault/config
            - name: data
              mountPath: /vault/data
          command: ["vault", "server", "-config=/vault/config/vault.hcl"]
      volumes:
        - name: config
          configMap:
            name: vault-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi